
import { ConstraintMemory } from '../agents/constraint-memory.js';
import { IntentClassifier } from '../kernel/classifier.js';
import { eventBus } from '../events/event-bus.js';
import { GeminiClient } from '../gemini/client.js';
import * as path from 'path';

// Mock file reading for demo environment where fs might not work as expected
const MOCK_LEGACY_CODE = `
/** 
 * Legacy Auth Module (Sample for Demo) 
 *  
 * This is a legacy-style file using: 
 * - var instead of let/const 
 * - callbacks instead of async/await 
 * - standard functions (NOT arrow functions - this is a CONSTRAINT) 
 */ 
 
var crypto = require('crypto'); 

function authenticate(user, password, callback) {
    var hash = crypto.createHash('sha256');
    hash.update(password);
    // ...
}
`;

export type LogCallback = (message: string) => void;

class GeminiReasoning {
    private client: GeminiClient;

    constructor() {
        // Use a default key or the one from env
        const apiKey = process.env.GEMINI_API_KEY || 'demo-key';
        this.client = new GeminiClient({ apiKey });
    }

    async plan(task: string, constraints: string): Promise<{
        summary: string;
        code: string;
        usesArrowFunctions: boolean;
    }> {
        // Construct prompt
        const prompt = `
You are an expert TypeScript developer.
TASK: ${task}

CONSTRAINTS:
${constraints}

INSTRUCTIONS:
1. Write the complete TypeScript code for the task.
2. STRICTLY ADHERE to the constraints.
3. Provide a brief summary of what you did.
4. Output specific JSON format.

RESPONSE FORMAT:
\`\`\`json
{
  "summary": "Brief summary of changes",
  "code": "The complete source code as a string",
  "usesArrowFunctions": boolean (true if you used '=>', false otherwise)
}
\`\`\`
`;

        eventBus.reasoningStart({ prompt: task, model: 'gemini-1.5-flash' });

        const result = await this.client.generate({
            prompt,
            config: {
                model: 'gemini-1.5-flash',
                temperature: 0.2,
            }
        });

        eventBus.reasoningComplete({ model: 'gemini-1.5-flash' });

        if (!result.ok) {
            // Fallback for demo resilience (Antigravity Agent)
            const mockCode = `
import { ConstraintMemory } from '../src/agents/constraint-memory.js';
import * as fs from 'fs/promises';

// MOCK IMPLEMENTATION BY ANTIGRAVITY AGENT
async function authenticate(user: string): Promise<boolean> {
    await delay(100);
    return true;
}

// Helper to simulate async work
function delay(ms: number): Promise<void> {
    return new Promise(function(resolve) { setTimeout(resolve, ms); });
}
`;
            return {
                summary: 'Generated by Antigravity Fallback Agent (API simulation)',
                code: mockCode,
                usesArrowFunctions: false
            };
        }

        const text = result.value.text;

        // Parse JSON from code block
        try {
            const jsonMatch = text.match(/```json\s*([\s\S]*?)```/);
            if (!jsonMatch) {
                const start = text.indexOf('{');
                const end = text.lastIndexOf('}');
                if (start !== -1 && end !== -1) {
                    return JSON.parse(text.substring(start, end + 1));
                }
                return JSON.parse(text);
            }
            return JSON.parse(jsonMatch[1]);
        } catch (e) {
            console.error('Failed to parse Gemini response:', text);
            return {
                summary: 'Failed to parse reasoning output, but code generation was attempted.',
                code: '// Error parsing generated code\n' + text,
                usesArrowFunctions: false
            };
        }
    }
}

class MockTestRunner {
    private runCount = 0;

    async run(code: string): Promise<{ passed: boolean; output: string; errors: string[] }> {
        this.runCount++;
        eventBus.emit('execution_complete', { file: 'test_runner', linesChanged: 0 }); // Simulate activity

        await new Promise(resolve => setTimeout(resolve, 600));

        // Check for arrow functions
        const hasArrowFunctions = code.includes('=>');

        if (hasArrowFunctions) {
            return {
                passed: false,
                output: 'FAIL auth.test.ts\n  ✕ should not use arrow functions in legacy module',
                errors: ['ESLint Error: Arrow functions are not allowed in legacy modules (no-arrow-functions)'],
            };
        }

        if (this.runCount === 1) {
            // First run fails (for demo)
            return {
                passed: false,
                output: 'FAIL auth.test.ts\n  ✕ should handle missing db connection',
                errors: ['TypeError: db.findUser is not a function'],
            };
        }

        return {
            passed: true,
            output: 'PASS auth.test.ts\n  ✓ authenticate\n  ✓ verifySession\n  ✓ logout\n  ✓ respects constraints',
            errors: [],
        };
    }
}

function delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
}

export async function runGoldenDemo(log: LogCallback) {
    log('\n');
    log('THE AMNESIAC REFACTOR - ContextOS Golden Run Demo');
    log('------------------------------------------------');
    log('\n');

    // Initialize components
    const memory = new ConstraintMemory();
    const classifier = new IntentClassifier();
    const reasoning = new GeminiReasoning();
    const testRunner = new MockTestRunner();

    const startTime = Date.now();

    // TURN 1: Constraint Injection
    log('👤 USER TURN 1: Constraint Injection');
    log('💬 "Hey, remember: never use arrow functions in the legacy module, only standard functions."');
    log('\n');

    await delay(500);

    // Memory gating
    const constraintInput = 'never use arrow functions in the legacy module, only standard functions';
    const entropy = 1.0;
    log(`   🚪[GATING] Entropy: ${entropy.toFixed(2)} → Gate OPEN`);

    // Store constraint
    memory.store(
        'forbid',
        'Never use arrow functions in legacy modules - use standard function declarations only',
        'auth',
        { priority: 10, source: 'user' }
    );

    log('\n   ✅ SYSTEM: Stored constraint in memory.\n');
    await delay(1000);

    // TURN 2: The Task
    log('👤 USER TURN 2: The Refactor Task');
    log('💬 "Refactor auth.ts to use Async/Await. Run tests when done."');
    log('\n');

    await delay(500);

    // Step 1: Intent Classification
    log('┌─ STEP 1: Intent Classification ─────────────────────────────────────┐');
    const taskInput = 'Refactor auth.ts to use Async/Await. Run tests when done.';
    const classification = classifier.classify({ input: taskInput });

    if (classification.ok) {
        const { intent, confidence } = classification.value;
        log(`│  Intent: ${intent.toUpperCase()}`);
        log(`│  Confidence: ${(confidence * 100).toFixed(0)}% `);
        log(`│  → Routing to Dev Teammate Agent`);
    }
    log('└──────────────────────────────────────────────────────────────────────┘\n');

    await delay(500);

    // Step 2: Context Retrieval
    log('┌─ STEP 2: Context Retrieval ──────────────────────────────────────────┐');
    const constraints = memory.recall('auth');
    log(`│  Scope: auth`);
    log(`│  Recalled: ${constraints.length} constraint(s)`);

    for (const c of constraints) {
        log(`│  📌[${c.type}] "${c.rule}"`);
    }
    log('└──────────────────────────────────────────────────────────────────────┘\n');

    await delay(500);

    // Step 3: Read Legacy File
    log('┌─ STEP 3: Reading Legacy File ────────────────────────────────────────┐');
    log('│  File: legacy-auth.js');
    log('│  Preview:');
    const lines = MOCK_LEGACY_CODE.split('\n').filter(l => l.trim().length > 0).slice(0, 5);
    for (const line of lines) {
        log(`│    ${line} `);
    }
    log('│    ...');
    log('└──────────────────────────────────────────────────────────────────────┘\n');

    // Self-Correcting Loop
    const maxAttempts = 3;
    const constraintContext = memory.formatForContext('auth');

    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
        log(`\n  🔄 ATTEMPT ${attempt}/${maxAttempts}`);
        log('------------------------------------------------');

        // Step 4: Reasoning
        log('\n┌─ STEP 4: Reasoning (Gemini) ────────────────────────────────────────┐');
        log('│  🧠 Thinking...');

        const plan = await reasoning.plan(taskInput, constraintContext);

        log(`│  Summary: ${plan.summary}`);
        log(`│  Uses Arrow Functions: ${plan.usesArrowFunctions ? '❌ YES' : '✅ NO'}`);
        log('└──────────────────────────────────────────────────────────────────────┘');

        // Check constraint violation before execution
        if (plan.usesArrowFunctions) {
            log('\n   ⚠️  CONSTRAINT VIOLATION DETECTED!');
            log('   📌 Rule: "Never use arrow functions in legacy modules"');
            log('   → Self-correcting: Regenerating with constraints...\n');
            await delay(500);
            continue;
        }

        // Step 5: Execution
        log('\n┌─ STEP 5: Executing Changes ─────────────────────────────────────────┐');
        log('│  📝 Writing refactored code...');
        log('│  File: src/auth.ts');
        log('│  Lines: ' + plan.code.split('\n').length);
        log('└──────────────────────────────────────────────────────────────────────┘');

        // Step 6: Testing
        log('\n┌─ STEP 6: Running Tests ─────────────────────────────────────────────┐');
        const testResult = await testRunner.run(plan.code);
        const outputLines = testResult.output.split('\n');
        for (const line of outputLines) {
            log(`│  ${line}`);
        }
        log('└──────────────────────────────────────────────────────────────────────┘');

        if (testResult.passed) {
            const duration = ((Date.now() - startTime) / 1000).toFixed(1);
            log('\n✅ SUCCESS!');
            log(`\n   ⏱️  Completed in ${duration}s (${attempt} attempt(s))`);
            log('\n   📝 Would create PR: "Refactor auth.ts to async/await"\n');
            return;
        }

        // Self-correct on test failure
        log('\n   ❌ Tests failed. Analyzing errors...');
        for (const error of testResult.errors) {
            log(`      ${error}`);
        }
        log('   → Self-correcting: Adjusting code...\n');
        await delay(500);
    }

    log('\n❌ FAILED: Max attempts exceeded\n');
}
