/**
 * Self-Contained Golden Run Demo for Vercel Serverless
 * 
 * This is a completely self-contained version that doesn't import
 * any modules from the src/ directory to avoid native module issues.
 */

import { GoogleGenerativeAI } from '@google/generative-ai';

export type LogCallback = (message: string) => void;

// ============================================================================
// Inline ConstraintMemory (simplified, in-memory only)
// ============================================================================

interface Constraint {
    id: string;
    type: 'forbid' | 'require' | 'prefer';
    rule: string;
    scope: string;
    priority: number;
    source: string;
    createdAt: number;
}

class ConstraintMemory {
    private constraints: Constraint[] = [];

    store(
        type: 'forbid' | 'require' | 'prefer',
        rule: string,
        scope: string,
        options: { priority?: number; source?: string } = {}
    ): Constraint {
        const constraint: Constraint = {
            id: crypto.randomUUID(),
            type,
            rule,
            scope,
            priority: options.priority ?? 5,
            source: options.source ?? 'system',
            createdAt: Date.now(),
        };
        this.constraints.push(constraint);
        return constraint;
    }

    recall(scope: string): Constraint[] {
        return this.constraints.filter(c => c.scope === scope || c.scope === '*');
    }

    formatForContext(scope: string): string {
        const constraints = this.recall(scope);
        if (constraints.length === 0) return 'No constraints for this scope.';
        return constraints
            .map(c => `[${c.type.toUpperCase()}] ${c.rule}`)
            .join('\n');
    }
}

// ============================================================================
// Inline IntentClassifier (simplified)
// ============================================================================

type Intent = 'workflow' | 'question' | 'command' | 'clarification' | 'unknown';

interface ClassificationResult {
    intent: Intent;
    confidence: number;
    latencyMs: number;
}

class IntentClassifier {
    classify(input: { input: string }): { ok: true; value: ClassificationResult } | { ok: false; error: Error } {
        const startTime = performance.now();
        const text = input.input.toLowerCase();

        let intent: Intent = 'unknown';
        let confidence = 0.5;

        // Simple keyword-based classification
        if (text.includes('refactor') || text.includes('implement') || text.includes('create') || text.includes('build')) {
            intent = 'workflow';
            confidence = 1.0;
        } else if (text.includes('?') || text.includes('what') || text.includes('how') || text.includes('why')) {
            intent = 'question';
            confidence = 0.9;
        } else if (text.includes('run') || text.includes('execute') || text.includes('do')) {
            intent = 'command';
            confidence = 0.85;
        }

        return {
            ok: true,
            value: {
                intent,
                confidence,
                latencyMs: performance.now() - startTime,
            },
        };
    }
}

// ============================================================================
// Inline GeminiReasoning (with fallback)
// ============================================================================

class GeminiReasoning {
    private genAI: GoogleGenerativeAI | null = null;

    constructor() {
        const apiKey = process.env.GEMINI_API_KEY;
        if (apiKey && apiKey !== 'demo-key') {
            this.genAI = new GoogleGenerativeAI(apiKey);
        }
    }

    async plan(task: string, constraints: string): Promise<{
        summary: string;
        code: string;
        usesArrowFunctions: boolean;
    }> {
        // Always use fallback for demo resilience
        const mockCode = `
import * as fs from 'fs/promises';

// IMPLEMENTATION BY ANTIGRAVITY AGENT
async function authenticate(user: string): Promise<boolean> {
    await delay(100);
    return true;
}

async function verifySession(token: string): Promise<boolean> {
    await delay(50);
    return token.length > 0;
}

async function logout(userId: string): Promise<void> {
    await delay(25);
    console.log('User logged out:', userId);
}

// Helper to simulate async work
function delay(ms: number): Promise<void> {
    return new Promise(function(resolve) { setTimeout(resolve, ms); });
}
`;
        return {
            summary: 'Generated by Antigravity Agent (self-contained demo)',
            code: mockCode,
            usesArrowFunctions: false
        };
    }
}

// ============================================================================
// Mock Test Runner
// ============================================================================

class MockTestRunner {
    private runCount = 0;

    async run(code: string): Promise<{ passed: boolean; output: string; errors: string[] }> {
        this.runCount++;
        await new Promise(resolve => setTimeout(resolve, 600));

        // Check for arrow functions
        const hasArrowFunctions = code.includes('=>');

        if (hasArrowFunctions) {
            return {
                passed: false,
                output: 'FAIL auth.test.ts\n  ✕ should not use arrow functions in legacy module',
                errors: ['ESLint Error: Arrow functions are not allowed in legacy modules'],
            };
        }

        if (this.runCount === 1) {
            return {
                passed: false,
                output: 'FAIL auth.test.ts\n  ✕ should handle missing db connection',
                errors: ['TypeError: db.findUser is not a function'],
            };
        }

        return {
            passed: true,
            output: 'PASS auth.test.ts\n  ✓ authenticate\n  ✓ verifySession\n  ✓ logout\n  ✓ respects constraints',
            errors: [],
        };
    }
}

// ============================================================================
// Mock Legacy Code
// ============================================================================

const MOCK_LEGACY_CODE = `
/** 
 * Legacy Auth Module (Sample for Demo) 
 * - var instead of let/const 
 * - callbacks instead of async/await 
 * - standard functions (NOT arrow functions) 
 */ 
 
var crypto = require('crypto'); 

function authenticate(user, password, callback) {
    var hash = crypto.createHash('sha256');
    hash.update(password);
    // ...
}
`;

// ============================================================================
// Helper
// ============================================================================

function delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
}

// ============================================================================
// Main Demo Runner
// ============================================================================

export async function runGoldenDemo(log: LogCallback) {
    log('\n');
    log('THE AMNESIAC REFACTOR - ContextOS Golden Run Demo');
    log('------------------------------------------------');
    log('Powered by Antigravity Agent (Vercel Serverless)');
    log('\n');

    // Initialize components
    const memory = new ConstraintMemory();
    const classifier = new IntentClassifier();
    const reasoning = new GeminiReasoning();
    const testRunner = new MockTestRunner();

    const startTime = Date.now();

    // TURN 1: Constraint Injection
    log('👤 USER TURN 1: Constraint Injection');
    log('💬 "Hey, remember: never use arrow functions in the legacy module, only standard functions."');
    log('\n');

    await delay(300);

    // Memory gating
    const entropy = 1.0;
    log(`   🚪[GATING] Entropy: ${entropy.toFixed(2)} → Gate OPEN`);

    // Store constraint
    memory.store(
        'forbid',
        'Never use arrow functions in legacy modules - use standard function declarations only',
        'auth',
        { priority: 10, source: 'user' }
    );

    log('\n   ✅ SYSTEM: Stored constraint in memory.\n');
    await delay(500);

    // TURN 2: The Task
    log('👤 USER TURN 2: The Refactor Task');
    log('💬 "Refactor auth.ts to use Async/Await. Run tests when done."');
    log('\n');

    await delay(300);

    // Step 1: Intent Classification
    log('┌─ STEP 1: Intent Classification ─────────────────────────────────────┐');
    const taskInput = 'Refactor auth.ts to use Async/Await. Run tests when done.';
    const classification = classifier.classify({ input: taskInput });

    if (classification.ok) {
        const { intent, confidence } = classification.value;
        log(`│  Intent: ${intent.toUpperCase()}`);
        log(`│  Confidence: ${(confidence * 100).toFixed(0)}% `);
        log(`│  → Routing to Dev Teammate Agent`);
    }
    log('└──────────────────────────────────────────────────────────────────────┘\n');

    await delay(300);

    // Step 2: Context Retrieval
    log('┌─ STEP 2: Context Retrieval ──────────────────────────────────────────┐');
    const constraints = memory.recall('auth');
    log(`│  Scope: auth`);
    log(`│  Recalled: ${constraints.length} constraint(s)`);

    for (const c of constraints) {
        log(`│  📌[${c.type}] "${c.rule}"`);
    }
    log('└──────────────────────────────────────────────────────────────────────┘\n');

    await delay(300);

    // Step 3: Read Legacy File
    log('┌─ STEP 3: Reading Legacy File ────────────────────────────────────────┐');
    log('│  File: legacy-auth.js');
    log('│  Preview:');
    const lines = MOCK_LEGACY_CODE.split('\n').filter(l => l.trim().length > 0).slice(0, 5);
    for (const line of lines) {
        log(`│    ${line} `);
    }
    log('│    ...');
    log('└──────────────────────────────────────────────────────────────────────┘\n');

    // Self-Correcting Loop
    const maxAttempts = 3;
    const constraintContext = memory.formatForContext('auth');

    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
        log(`\n  🔄 ATTEMPT ${attempt}/${maxAttempts}`);
        log('------------------------------------------------');

        // Step 4: Reasoning
        log('\n┌─ STEP 4: Reasoning (Antigravity Agent) ─────────────────────────────┐');
        log('│  🧠 Thinking...');

        const plan = await reasoning.plan(taskInput, constraintContext);

        log(`│  Summary: ${plan.summary}`);
        log(`│  Uses Arrow Functions: ${plan.usesArrowFunctions ? '❌ YES' : '✅ NO'}`);
        log('└──────────────────────────────────────────────────────────────────────┘');

        // Check constraint violation
        if (plan.usesArrowFunctions) {
            log('\n   ⚠️  CONSTRAINT VIOLATION DETECTED!');
            log('   📌 Rule: "Never use arrow functions in legacy modules"');
            log('   → Self-correcting: Regenerating with constraints...\n');
            await delay(300);
            continue;
        }

        // Step 5: Execution
        log('\n┌─ STEP 5: Executing Changes ─────────────────────────────────────────┐');
        log('│  📝 Writing refactored code...');
        log('│  File: src/auth.ts');
        log('│  Lines: ' + plan.code.split('\n').length);
        log('└──────────────────────────────────────────────────────────────────────┘');

        // Step 6: Testing
        log('\n┌─ STEP 6: Running Tests ─────────────────────────────────────────────┐');
        const testResult = await testRunner.run(plan.code);
        const outputLines = testResult.output.split('\n');
        for (const line of outputLines) {
            log(`│  ${line}`);
        }
        log('└──────────────────────────────────────────────────────────────────────┘');

        if (testResult.passed) {
            const duration = ((Date.now() - startTime) / 1000).toFixed(1);
            log('\n✅ SUCCESS!');
            log(`\n   ⏱️  Completed in ${duration}s (${attempt} attempt(s))`);
            log('\n   📝 Would create PR: "Refactor auth.ts to async/await"\n');
            return;
        }

        // Self-correct on test failure
        log('\n   ❌ Tests failed. Analyzing errors...');
        for (const error of testResult.errors) {
            log(`      ${error}`);
        }
        log('   → Self-correcting: Adjusting code...\n');
        await delay(300);
    }

    log('\n❌ FAILED: Max attempts exceeded\n');
}
